wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [26, 15, 15, 15]
    # How _high_ the rows are, in terminal lines.
    rows: [2, 2, 2, 2, 2, 4, 4, 4, 4]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    prettyweather:
      title: "Weather (DLH)"
      enabled: true
      city: "DLH"
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 3600
      unit: "u"
      view: "0nQF"
      language: "en"

    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    istats:
      type: cmdrunner
      cmd: combined-stats
      title: "⚡️"
      enabled: true
      position:
        top: 4
        left: 2
        height: 3
        width: 2
      refreshInterval: 90

    resources:
      type: resourceusage
      enabled: true
      position:
        top: 4
        left: 0
        height: 5
        width: 2
      refreshInterval: 10
    count:
      title: Counts
      type: cmdrunner
      cmd: "counts" # see dotfiles/bin/counts
      enabled: true
      refreshInterval: 300
      position:
        top: 0
        left: 1
        height: 4
        width: 3
