wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters.
    columns: [15, 15, 15, 9, 5, 24]
    # How _high_ the rows are, in terminal lines.
    rows: [2, 2, 3, 2, 2, 4, 4, 4, 4]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    prettyweather:
      title: "Weather (DLH)"
      enabled: false
      city: "DLH"
      position:
        top: 0
        left: 0
        height: 4
        width: 2
      refreshInterval: 7200
      unit: "u"
      view: "0nQF"
      language: "en"

    count:
      title: Counts
      type: cmdrunner
      cmd: "counts" # see dotfiles/bin/counts
      enabled: true
      refreshInterval: 300
      position:
        top: 0
        left: 0
        height: 4
        width: 4
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    power:
      # type: cmdrunner
      # cmd: combined-stats
      title: "⚡️"
      enabled: true
      position:
        top: 0
        left: 4
        height: 4
        width: 2
      refreshInterval: 90
