wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 31, 39, 35]
    # How _high_ the rows are, in terminal lines.
    rows: [2, 2, 5, 7, 8, 7, 4]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    prettyweather:
      title: "Weather (DLH)"
      enabled: true
      city: "DLH"
      position:
        top: 0
        left: 0
        height: 4
        width: 2
      refreshInterval: 1200
      unit: "u"
      view: "1nQF"
      language: "en"
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 4
        left: 0
        height: 2
        width: 1
      refreshInterval: 60

    resources:
      type: resourceusage
      enabled: true
      position:
        top: 2
        left: 2
        height: 5
        width: 2
      refreshInterval: 4
    git:
      commitCount: 7
      enabled: false
      position:
        top: 4
        left: 1
        height: 3
        width: 3
      refreshInterval: 30
      repositories:
        - "/Users/blaed/code/rails/k2"
    count:
      title: Counts
      type: cmdrunner
      cmd: "counts" # see dotfiled/bin/counts
      enabled: true
      refreshInterval: 300
      position:
        top: 0
        left: 2
        height: 2
        width: 1
